### ISSUE TITLE
sbt server/run doesn't compile

### ISSUE THREAD

**Issue by matitalatina** [Insubric/box#183]
## Environment
Mac OS Big Sur 11.4
java 12.0.2 2019-07-16
sbt 1.5.0 (Homebrew Java 16.0.1)
Scala code runner version 2.13.6 

## Steps to reproduce

- Clone this project (master 4f886b9d5b4dae044bb11006a7a94ca60cbf6a50)
- Run `sbt server/run`

Compilation fails
```
[info] welcome to sbt 1.5.0 (Homebrew Java 16.0.1)
[info] loading global plugins from /Users/mattia/.sbt/1.0/plugins
[info] loading settings for project box-build from plugins.sbt ...
[info] loading project definition from /Users/mattia/Repositories/box/project
[info] compiling 2 Scala sources to /Users/mattia/Repositories/box/project/target/scala-2.12/sbt-1.0/classes ...
[warn] one feature warning; re-run with -feature for details
[warn] one warning found
[info] loading settings for project box from build.sbt ...
[info] set current project to box (in build file:/Users/mattia/Repositories/box/)
[warn] there are 23 keys that are not used by any other settings/tasks:
[warn]  
[warn] * ThisBuild / developers
[warn]   +- /Users/mattia/Repositories/box/build.sbt:35
[warn] * ThisBuild / homepage
[warn]   +- /Users/mattia/Repositories/box/build.sbt:35
[warn] * ThisBuild / licenses
[warn]   +- /Users/mattia/Repositories/box/build.sbt:35
[warn] * ThisBuild / organization
[warn]   +- /Users/mattia/Repositories/box/build.sbt:35
[warn] * ThisBuild / pomIncludeRepository
[warn]   +- /Users/mattia/Repositories/box/build.sbt:35
[warn] * ThisBuild / publishMavenStyle
[warn]   +- /Users/mattia/Repositories/box/build.sbt:35
[warn] * ThisBuild / scmInfo
[warn]   +- /Users/mattia/Repositories/box/build.sbt:35
[warn] * box / dynverSeparator
[warn]   +- /Users/mattia/Repositories/box/build.sbt:17
[warn] * box / dynverSonatypeSnapshots
[warn]   +- /Users/mattia/Repositories/box/build.sbt:25
[warn] * client / dynverSeparator
[warn]   +- /Users/mattia/Repositories/box/build.sbt:17
[warn] * client / dynverSonatypeSnapshots
[warn]   +- /Users/mattia/Repositories/box/build.sbt:25
[warn] * codegen / dynverSeparator
[warn]   +- /Users/mattia/Repositories/box/build.sbt:17
[warn] * codegen / dynverSonatypeSnapshots
[warn]   +- /Users/mattia/Repositories/box/build.sbt:25
[warn] * server / dynverSeparator
[warn]   +- /Users/mattia/Repositories/box/build.sbt:17
[warn] * server / dynverSonatypeSnapshots
[warn]   +- /Users/mattia/Repositories/box/build.sbt:25
[warn] * serverCacheRedis / dynverSeparator
[warn]   +- /Users/mattia/Repositories/box/build.sbt:17
[warn] * serverCacheRedis / dynverSonatypeSnapshots
[warn]   +- /Users/mattia/Repositories/box/build.sbt:25
[warn] * serverServices / dynverSeparator
[warn]   +- /Users/mattia/Repositories/box/build.sbt:17
[warn] * serverServices / dynverSonatypeSnapshots
[warn]   +- /Users/mattia/Repositories/box/build.sbt:25
[warn] * sharedJS / dynverSeparator
[warn]   +- /Users/mattia/Repositories/box/build.sbt:17
[warn] * sharedJS / dynverSonatypeSnapshots
[warn]   +- /Users/mattia/Repositories/box/build.sbt:25
[warn] * sharedJVM / dynverSeparator
[warn]   +- /Users/mattia/Repositories/box/build.sbt:17
[warn] * sharedJVM / dynverSonatypeSnapshots
[warn]   +- /Users/mattia/Repositories/box/build.sbt:25
[warn]  
[warn] note: a setting might still be used by a command; to exclude a key from this `lintUnused` check
[warn] either append it to `Global / excludeLintKeys` or call .withRank(KeyRanks.Invisible) on the key
[info] compiling 28 Scala sources to /Users/mattia/Repositories/box/shared/.jvm/target/scala-2.12/classes ...
[info] compiling 28 Scala sources to /Users/mattia/Repositories/box/shared/.js/target/scala-2.13/classes ...
[warn] 7 deprecations (since 2.13.0); re-run with -deprecation for details
[warn] one warning found
[info] compiling 90 Scala sources to /Users/mattia/Repositories/box/client/target/scala-2.13/classes ...
[info] compiling 1 Scala source to /Users/mattia/Repositories/box/server-services/target/scala-2.12/classes ...
[info] compiling 19 Scala sources to /Users/mattia/Repositories/box/codegen/target/scala-2.12/classes ...
[warn] there was one deprecation warning (since 3.2); re-run with -deprecation for details
[warn] one warning found
[warn] 3 deprecations
[warn] 22 deprecations (since 0.5.3)
[warn] 1 deprecation (since 2.11.0)
[warn] 24 deprecations (since 2.13.0)
[warn] 4 deprecations (since 2.13.3)
[warn] 54 deprecations in total; re-run with -deprecation for details
[warn] 6 warnings found
[info] Fast optimizing /Users/mattia/Repositories/box/client/target/scala-2.13/client-fastopt
[info] compiling 130 Scala sources to /Users/mattia/Repositories/box/server/target/scala-2.12/classes ...
[error] /Users/mattia/Repositories/box/server/src/main/scala/ch/wsl/box/model/BuildBox.scala:747:61: no type parameters for method map: (x$1: java.util.function.Function[_ >: String, _ <: R])java.util.stream.Stream[R] exist so that it can be applied to arguments (java.util.function.Function[String,Array[String]])
[error]  --- because ---
[error] argument expression's type is not compatible with formal parameter type;
[error]  found   : java.util.function.Function[String,Array[String]]
[error]  required: java.util.function.Function[_ >: String, _ <: ?R]
[error] Note: String <: Any, but Java-defined trait Function is invariant in type T.
[error] You may wish to investigate a wildcard type such as `_ <: Any`. (SLS 3.2.10)
[error]   val labels:Seq[BoxLabels.BoxLabels_row] = rawLabels.lines.map(_.split("\\t")).filterNot(_.length < 3).map{ line =>
[error]                                                             ^
[error] /Users/mattia/Repositories/box/server/src/main/scala/ch/wsl/box/model/BuildBox.scala:747:72: type mismatch;
[error]  found   : java.util.function.Function[String,Array[String]]
[error]  required: java.util.function.Function[_ >: String, _ <: R]
[error]   val labels:Seq[BoxLabels.BoxLabels_row] = rawLabels.lines.map(_.split("\\t")).filterNot(_.length < 3).map{ line =>
[error]                                                                        ^
[error] /Users/mattia/Repositories/box/server/src/main/scala/ch/wsl/box/model/BuildBox.scala:747:81: value filterNot is not a member of java.util.stream.Stream[R]
[error]   val labels:Seq[BoxLabels.BoxLabels_row] = rawLabels.lines.map(_.split("\\t")).filterNot(_.length < 3).map{ line =>
[error]                                                                                 ^
[error] /Users/mattia/Repositories/box/server/src/main/scala/ch/wsl/box/rest/runtime/Registry.scala:27:60: value drop is not a member of java.util.stream.Stream[String]
[error]   private def dropPackage(code:String):String = code.lines.drop(1).mkString("\n")
[error]                                                            ^
[error] four errors found
[error] (server / Compile / compileIncremental) Compilation failed
[error] Total time: 298 s (04:58), completed Jul 16, 2021, 6:35:39 PM

```

**Comment by minettiandrea** [comment]
Hi Mattia,
thank you for reporting,
I was able to reproduce using the JDK 12, I suppose is a scala compiler issue.

looking at https://docs.scala-lang.org/overviews/jdk-compatibility/overview.html#running-versus-compiling is advised to use JDK 8 or 11, in my env and CI I always use JDK 8 since it looks like the safer choice for scala.

That is definitely something to add on the docs. 

Let me know if using another version of JDK it works

**Comment by matitalatina** [comment]
It doesn't work with java 11.0.11 2021-04-20 LTS. Same result.
It works with JDK 8, but I need to start with
```bash
sbt -mem 2048 server/run
```
otherwise I have an OutOfMemory error during compilation. [I found the solution here](https://stackoverflow.com/questions/54682907/on-scala-project-getting-error-gc-overhead-limit-exceeded-when-running-sbt-tes).

Now I have this error, but I think it's a configuration problem, so for me this is solved.

```
[info] running ch.wsl.box.rest.Boot 
[error] (run-main-0) com.typesafe.config.ConfigException$Missing: merge of system properties,reference.conf @ jar:file:/Users/mattia/Repositories/box/target/bg-jobs/sbt_8458e05c/target/bd29211f/5f171d04/slick_2.12-3.3.3.jar!/reference.conf: 1,reference.conf @ jar:file:/Users/mattia/Repositories/box/target/bg-jobs/sbt_8458e05c/target/a4bb22a6/93642e6d/akka-http-core_2.12-10.1.11.jar!/reference.conf: 1,reference.conf @ jar:file:/Users/mattia/Repositories/box/target/bg-jobs/sbt_8458e05c/target/c5c29761/39bf5eff/akka-http-caching_2.12-10.1.11.jar!/reference.conf: 1,reference.conf @ jar:file:/Users/mattia/Repositories/box/target/bg-jobs/sbt_8458e05c/target/c3099855/36c8309c/akka-actor_2.12-2.6.4.jar!/reference.conf: 1,reference.conf @ jar:file:/Users/mattia/Repositories/box/target/bg-jobs/sbt_8458e05c/target/a29407e0/3d03f5ec/akka-stream_2.12-2.6.4.jar!/reference.conf: 1,reference.conf @ jar:file:/Users/mattia/Repositories/box/target/bg-jobs/sbt_8458e05c/target/60a34ca7/a5bf3134/akka-quartz-scheduler_2.12-1.8.5-akka-2.6.x.jar!/reference.conf: 1,reference.conf @ jar:file:/Users/mattia/Repositories/box/target/bg-jobs/sbt_8458e05c/target/a3ee1537/9e1d6d00/core_2.12-0.5.11.jar!/reference.conf: 1,reference.conf @ jar:file:/Users/mattia/Repositories/box/target/bg-jobs/sbt_8458e05c/target/fa2b957f/5a4eaa49/scredis_2.12-2.4.3.jar!/reference.conf: 1,reference.conf @ jar:file:/Users/mattia/Repositories/box/target/bg-jobs/sbt_8458e05c/target/b5ae5125/21c8e212/akka-http_2.12-10.1.11.jar!/reference.conf: 1,reference.conf @ jar:file:/Users/mattia/Repositories/box/target/bg-jobs/sbt_8458e05c/target/7c87c9e4/fca8c727/ssl-config-core_2.12-0.4.1.jar!/reference.conf: 1,reference.conf @ jar:file:/Users/mattia/Repositories/box/target/bg-jobs/sbt_8458e05c/target/4b2d7cf1/967748b1/geotrellis-vector_2.12-3.2.0.jar!/reference.conf: 1: No configuration setting found for key 'db'
[error] com.typesafe.config.ConfigException$Missing: merge of system properties,reference.conf @ jar:file:/Users/mattia/Repositories/box/target/bg-jobs/sbt_8458e05c/target/bd29211f/5f171d04/slick_2.12-3.3.3.jar!/reference.conf: 1,reference.conf @ jar:file:/Users/mattia/Repositories/box/target/bg-jobs/sbt_8458e05c/target/a4bb22a6/93642e6d/akka-http-core_2.12-10.1.11.jar!/reference.conf: 1,reference.conf @ jar:file:/Users/mattia/Repositories/box/target/bg-jobs/sbt_8458e05c/target/c5c29761/39bf5eff/akka-http-caching_2.12-10.1.11.jar!/reference.conf: 1,reference.conf @ jar:file:/Users/mattia/Repositories/box/target/bg-jobs/sbt_8458e05c/target/c3099855/36c8309c/akka-actor_2.12-2.6.4.jar!/reference.conf: 1,reference.conf @ jar:file:/Users/mattia/Repositories/box/target/bg-jobs/sbt_8458e05c/target/a29407e0/3d03f5ec/akka-stream_2.12-2.6.4.jar!/reference.conf: 1,reference.conf @ jar:file:/Users/mattia/Repositories/box/target/bg-jobs/sbt_8458e05c/target/60a34ca7/a5bf3134/akka-quartz-scheduler_2.12-1.8.5-akka-2.6.x.jar!/reference.conf: 1,reference.conf @ jar:file:/Users/mattia/Repositories/box/target/bg-jobs/sbt_8458e05c/target/a3ee1537/9e1d6d00/core_2.12-0.5.11.jar!/reference.conf: 1,reference.conf @ jar:file:/Users/mattia/Repositories/box/target/bg-jobs/sbt_8458e05c/target/fa2b957f/5a4eaa49/scredis_2.12-2.4.3.jar!/reference.conf: 1,reference.conf @ jar:file:/Users/mattia/Repositories/box/target/bg-jobs/sbt_8458e05c/target/b5ae5125/21c8e212/akka-http_2.12-10.1.11.jar!/reference.conf: 1,reference.conf @ jar:file:/Users/mattia/Repositories/box/target/bg-jobs/sbt_8458e05c/target/7c87c9e4/fca8c727/ssl-config-core_2.12-0.4.1.jar!/reference.conf: 1,reference.conf @ jar:file:/Users/mattia/Repositories/box/target/bg-jobs/sbt_8458e05c/target/4b2d7cf1/967748b1/geotrellis-vector_2.12-3.2.0.jar!/reference.conf: 1: No configuration setting found for key 'db'
[error]         at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:156)
[error]         at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:174)
[error]         at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
[error]         at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
[error]         at com.typesafe.config.impl.SimpleConfig.getObject(SimpleConfig.java:268)
[error]         at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:274)
[error]         at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:41)
[error]         at net.ceedubs.ficus.readers.ConfigReader$$anon$1.read(ConfigReader.scala:8)
[error]         at net.ceedubs.ficus.readers.ConfigReader$$anon$1.read(ConfigReader.scala:7)
[error]         at net.ceedubs.ficus.FicusConfig.as(FicusConfig.scala:10)
[error]         at net.ceedubs.ficus.FicusConfig.as$(FicusConfig.scala:10)
[error]         at net.ceedubs.ficus.SimpleFicusConfig.as(FicusConfig.scala:21)
[error]         at ch.wsl.box.jdbc.ConnectionConfImpl.<init>(Connection.scala:66)
[error]         at ch.wsl.box.rest.DefaultModule$$anon$4.<init>(Module.scala:21)
[error]         at ch.wsl.box.rest.DefaultModule$.$anonfun$injector$4(Module.scala:21)
[error]         at ch.wsl.box.rest.DefaultModule$$$Lambda$8750/44710052.apply(Unknown Source)
[error]         at wvlet.airframe.AirframeSession.$anonfun$buildInstance$1(AirframeSession.scala:393)
[error]         at wvlet.airframe.AirframeSession$$Lambda$8778/20582724.apply(Unknown Source)
[error]         at scala.Option.map(Option.scala:230)
[error]         at wvlet.airframe.AirframeSession.buildInstance(AirframeSession.scala:391)
[error]         at wvlet.airframe.AirframeSession.$anonfun$getInstance$8(AirframeSession.scala:371)
[error]         at wvlet.airframe.AirframeSession$$Lambda$8788/1862486393.apply(Unknown Source)
[error]         at scala.collection.concurrent.Map.getOrElseUpdate(Map.scala:97)
[error]         at scala.collection.concurrent.Map.getOrElseUpdate$(Map.scala:94)
[error]         at scala.collection.convert.Wrappers$JConcurrentMapWrapper.getOrElseUpdate(Wrappers.scala:333)
[error]         at wvlet.airframe.AirframeSession.$anonfun$getInstance$7(AirframeSession.scala:368)
[error]         at wvlet.airframe.AirframeSession$$Lambda$8787/417204520.apply(Unknown Source)
[error]         at scala.Option.getOrElse(Option.scala:189)
[error]         at wvlet.airframe.AirframeSession.getInstance(AirframeSession.scala:350)
[error]         at wvlet.airframe.AirframeSession.$anonfun$getInstance$3(AirframeSession.scala:318)
[error]         at wvlet.airframe.AirframeSession$$Lambda$8792/447131807.apply(Unknown Source)
[error]         at scala.collection.concurrent.Map.getOrElseUpdate(Map.scala:97)
[error]         at scala.collection.concurrent.Map.getOrElseUpdate$(Map.scala:94)
[error]         at scala.collection.convert.Wrappers$JConcurrentMapWrapper.getOrElseUpdate(Wrappers.scala:333)
[error]         at wvlet.airframe.AirframeSession.getInstance(AirframeSession.scala:308)
[error]         at wvlet.airframe.AirframeSession.get(AirframeSession.scala:167)
[error]         at wvlet.airframe.Session$SessionAccess$.get$extension(Session.scala:152)
[error]         at ch.wsl.box.services.files.PgImageCacheStorage.$anonfun$connection$1(PgImageCacheStorage.scala:14)
[error]         at ch.wsl.box.services.files.PgImageCacheStorage$$Lambda$8793/513458266.apply(Unknown Source)
[error]         at ch.wsl.box.services.files.PgImageCacheStorage.<init>(PgImageCacheStorage.scala:14)
[error]         at ch.wsl.box.rest.DefaultModule$$anon$2.<init>(Module.scala:19)
[error]         at ch.wsl.box.rest.DefaultModule$.$anonfun$injector$2(Module.scala:19)
[error]         at ch.wsl.box.rest.DefaultModule$$$Lambda$8748/1031812138.apply(Unknown Source)
[error]         at wvlet.airframe.AirframeSession.$anonfun$buildInstance$1(AirframeSession.scala:393)
[error]         at wvlet.airframe.AirframeSession$$Lambda$8778/20582724.apply(Unknown Source)
[error]         at scala.Option.map(Option.scala:230)
[error]         at wvlet.airframe.AirframeSession.buildInstance(AirframeSession.scala:391)
[error]         at wvlet.airframe.AirframeSession.$anonfun$getInstance$8(AirframeSession.scala:371)
[error]         at wvlet.airframe.AirframeSession$$Lambda$8788/1862486393.apply(Unknown Source)
[error]         at scala.collection.concurrent.Map.getOrElseUpdate(Map.scala:97)
[error]         at scala.collection.concurrent.Map.getOrElseUpdate$(Map.scala:94)
[error]         at scala.collection.convert.Wrappers$JConcurrentMapWrapper.getOrElseUpdate(Wrappers.scala:333)
[error]         at wvlet.airframe.AirframeSession.$anonfun$getInstance$7(AirframeSession.scala:368)
[error]         at wvlet.airframe.AirframeSession$$Lambda$8787/417204520.apply(Unknown Source)
[error]         at scala.Option.getOrElse(Option.scala:189)
[error]         at wvlet.airframe.AirframeSession.getInstance(AirframeSession.scala:350)
[error]         at wvlet.airframe.AirframeSession.$anonfun$getInstance$3(AirframeSession.scala:318)
[error]         at wvlet.airframe.AirframeSession$$Lambda$8792/447131807.apply(Unknown Source)
[error]         at scala.collection.concurrent.Map.getOrElseUpdate(Map.scala:97)
[error]         at scala.collection.concurrent.Map.getOrElseUpdate$(Map.scala:94)
[error]         at scala.collection.convert.Wrappers$JConcurrentMapWrapper.getOrElseUpdate(Wrappers.scala:333)
[error]         at wvlet.airframe.AirframeSession.getInstance(AirframeSession.scala:308)
[error]         at wvlet.airframe.AirframeSession.get(AirframeSession.scala:167)
[error]         at wvlet.airframe.Session$SessionAccess$.get$extension(Session.scala:152)
[error]         at ch.wsl.box.services.files.ImageCache.$anonfun$storage$1(ImageCache.scala:23)
[error]         at ch.wsl.box.services.files.ImageCache$$Lambda$8791/1508761907.apply(Unknown Source)
[error]         at ch.wsl.box.services.files.ImageCache.$init$(ImageCache.scala:23)
[error]         at ch.wsl.box.services.Services$$anon$1.<init>(Services.scala:12)
[error]         at ch.wsl.box.services.Services.$anonfun$imageCacher$2(Services.scala:12)
[error]         at ch.wsl.box.services.Services$$Lambda$8785/1374002882.apply(Unknown Source)
[error]         at wvlet.airframe.AirframeSession.$anonfun$buildInstance$3(AirframeSession.scala:399)
[error]         at wvlet.airframe.AirframeSession$$Lambda$8790/2069964633.apply(Unknown Source)
[error]         at scala.Option.map(Option.scala:230)
[error]         at wvlet.airframe.AirframeSession.$anonfun$buildInstance$2(AirframeSession.scala:397)
[error]         at wvlet.airframe.AirframeSession$$Lambda$8789/133995256.apply(Unknown Source)
[error]         at scala.Option.orElse(Option.scala:447)
[error]         at wvlet.airframe.AirframeSession.buildInstance(AirframeSession.scala:397)
[error]         at wvlet.airframe.AirframeSession.$anonfun$getInstance$8(AirframeSession.scala:371)
[error]         at wvlet.airframe.AirframeSession$$Lambda$8788/1862486393.apply(Unknown Source)
[error]         at scala.collection.concurrent.Map.getOrElseUpdate(Map.scala:97)
[error]         at scala.collection.concurrent.Map.getOrElseUpdate$(Map.scala:94)
[error]         at scala.collection.convert.Wrappers$JConcurrentMapWrapper.getOrElseUpdate(Wrappers.scala:333)
[error]         at wvlet.airframe.AirframeSession.$anonfun$getInstance$7(AirframeSession.scala:368)
[error]         at wvlet.airframe.AirframeSession$$Lambda$8787/417204520.apply(Unknown Source)
[error]         at scala.Option.getOrElse(Option.scala:189)
[error]         at wvlet.airframe.AirframeSession.getInstance(AirframeSession.scala:350)
[error]         at wvlet.airframe.AirframeSession.getOrElse(AirframeSession.scala:172)
[error]         at wvlet.airframe.Session$SessionAccess$.getOrElse$extension(Session.scala:154)
[error]         at ch.wsl.box.services.Services.$anonfun$imageCacher$1(Services.scala:12)
[error]         at ch.wsl.box.services.Services$$Lambda$8784/902362589.apply(Unknown Source)
[error]         at ch.wsl.box.services.Services.$init$(Services.scala:12)
[error]         at ch.wsl.box.rest.DefaultModule$$anon$1.<init>(Module.scala:24)
[error]         at ch.wsl.box.rest.DefaultModule$.$anonfun$injector$1(Module.scala:24)
[error]         at ch.wsl.box.rest.DefaultModule$$$Lambda$8736/921331345.apply(Unknown Source)
[error]         at wvlet.airframe.AirframeSession.$anonfun$buildInstance$1(AirframeSession.scala:393)
[error]         at wvlet.airframe.AirframeSession$$Lambda$8778/20582724.apply(Unknown Source)
[error]         at scala.Option.map(Option.scala:230)
[error]         at wvlet.airframe.AirframeSession.buildInstance(AirframeSession.scala:391)
[error]         at wvlet.airframe.AirframeSession.$anonfun$getInstance$4(AirframeSession.scala:329)
[error]         at wvlet.airframe.AirframeSession$$Lambda$8777/2120979806.apply(Unknown Source)
[error]         at scala.collection.concurrent.Map.getOrElseUpdate(Map.scala:97)
[error]         at scala.collection.concurrent.Map.getOrElseUpdate$(Map.scala:94)
[error]         at scala.collection.convert.Wrappers$JConcurrentMapWrapper.getOrElseUpdate(Wrappers.scala:333)
[error]         at wvlet.airframe.AirframeSession.getInstance(AirframeSession.scala:326)
[error]         at wvlet.airframe.AirframeSession.getInstanceOf(AirframeSession.scala:107)
[error]         at wvlet.airframe.AirframeSession$$anonfun$init$1.applyOrElse(AirframeSession.scala:157)
[error]         at wvlet.airframe.AirframeSession$$anonfun$init$1.applyOrElse(AirframeSession.scala:155)
[error]         at scala.PartialFunction.$anonfun$runWith$1$adapted(PartialFunction.scala:145)
[error]         at scala.PartialFunction$$Lambda$8770/1723216041.apply(Unknown Source)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:943)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error]         at scala.collection.TraversableLike.collect(TraversableLike.scala:406)
[error]         at scala.collection.TraversableLike.collect$(TraversableLike.scala:404)
[error]         at scala.collection.AbstractTraversable.collect(Traversable.scala:108)
[error]         at wvlet.airframe.AirframeSession.init(AirframeSession.scala:155)
[error]         at wvlet.airframe.SessionBuilder.create(SessionBuilder.scala:100)
[error]         at wvlet.airframe.Design.newSession(Design.scala:284)
[error]         at wvlet.airframe.Design.withSession(Design.scala:303)
[error]         at ch.wsl.box.rest.Boot$.run(Boot.scala:127)
[error]         at ch.wsl.box.rest.Boot$.delayedEndpoint$ch$wsl$box$rest$Boot$1(Boot.scala:134)
[error]         at ch.wsl.box.rest.Boot$delayedInit$body.apply(Boot.scala:111)
[error]         at scala.Function0.apply$mcV$sp(Function0.scala:39)
[error]         at scala.Function0.apply$mcV$sp$(Function0.scala:39)
[error]         at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
[error]         at scala.App.$anonfun$main$1$adapted(App.scala:80)
[error]         at scala.App$$Lambda$8511/729380524.apply(Unknown Source)
[error]         at scala.collection.immutable.List.foreach(List.scala:431)
[error]         at scala.App.main(App.scala:80)
[error]         at scala.App.main$(App.scala:78)
[error]         at ch.wsl.box.rest.Boot$.main(Boot.scala:111)
[error]         at ch.wsl.box.rest.Boot.main(Boot.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:497)
[error] stack trace is suppressed; run last server / Compile / bgRun for the full output
[error] Nonzero exit code: 1
[error] (server / Compile / run) Nonzero exit code: 1
[error] Total time: 121 s (02:01), completed Jul 17, 2021 12:08:17 PM
```
